-- Role-Based Access Control (RBAC) Setup
CREATE ROLE IF NOT EXISTS TRANSFORMER_DEV;
CREATE ROLE IF NOT EXISTS TRANSFORMER_PROD;

-- Grant Database & Schema Access to Transformer Roles
GRANT USAGE ON WAREHOUSE HEALTHCARE_WH TO ROLE TRANSFORMER_DEV;
GRANT USAGE ON WAREHOUSE HEALTHCARE_WH TO ROLE TRANSFORMER_PROD;

GRANT ALL ON DATABASE HEALTHCARE_DEV_DB TO ROLE TRANSFORMER_DEV;
GRANT ALL ON DATABASE HEALTHCARE_PROD_DB TO ROLE TRANSFORMER_PROD;

GRANT ALL ON ALL SCHEMAS IN DATABASE HEALTHCARE_PROD_DB TO ROLE TRANSFORMER_PROD;
GRANT ALL ON ALL SCHEMAS IN DATABASE HEALTHCARE_DEV_DB TO ROLE TRANSFORMER_DEV;

-- Create Service User for CI/CD Pipeline
CREATE USER IF NOT EXISTS CICD_DBT_USER
    PASSWORD = 'DemoPassword123!' -- Replace in production with Key Pair Authentication
    DEFAULT_ROLE = TRANSFORMER_DEV
    DEFAULT_WAREHOUSE = HEALTHCARE_WH
    MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE TRANSFORMER_DEV TO USER CICD_DBT_USER;
GRANT ROLE TRANSFORMER_PROD TO USER CICD_DBT_USER;